name: GIT ENV

on: [push]

env: 
  WF_ENV: Available to all jobs

jobs: 
  log-env: 
    runs-on: ubuntu-latest
    env: 
      JOB_ENV: Available to all steps in log-env
    steps:
      - name: echo step 1
        env: 
          STEP_ENV: Available only this step
        run: | 
          echo "WF_ENV": ${WF_ENV}
          echo "JOB_ENV": ${JOB_ENV}
          echo "STEP_ENV": ${STEP_ENV}
      - name: echo step 2
        run: | 
          echo "WF_ENV": ${WF_ENV}
          echo "JOB_ENV": ${JOB_ENV}
          echo "STEP_ENV": ${STEP_ENV}
  log-defaul-env:
    runs-on: ubuntu-latest
    steps:
      - name: echo default env
        run: |
          echo "GITHUB_ACTION": ${GITHUB_ACTION}
          echo "GITHUB_ACTIONS": ${GITHUB_ACTIONS}
          echo "GITHUB_WORKFLOW": ${GITHUB_WORKFLOW}
          echo "GITHUB_ACTOR": ${GITHUB_ACTOR}
          echo "GITHUB_EVENT_NAME": ${GITHUB_EVENT_NAME}
