name: TEST_ACTION PR

on:
  schedule:
    -cron: "0/5 * * * *"
  pull_request:
    types: [closed, assigned, opened, reopened]
jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: ECHO SOMeTHING
        run: echo $GITHUB_REPOSITORY